### ISSUE TITLE
Screenshots should not include background images

### ISSUE THREAD

**Issue by danirabbit** [alexkdeveloper/bmi#1]
Hey there! While reviewing your app submission for AppCenter I noticed that your screenshots include a background image. As per our [publishing guidelines](https://docs.elementary.io/develop/appcenter/publishing-requirements), screenshots should only include your app and shouldn't include any other illustrations including backgrounds.

**Comment by alexkdeveloper** [comment]
Привет !
Я извиняюсь. 
Но может быть есть смысл изменить надпись в приложении Gender на какую-нибудь другую?
Например, я предлагаю надпись на пол.

**Comment by alexkdeveloper** [comment]
Hi!
I was thinking, maybe it makes sense to change the gender labeling to gender?

**Comment by alexkdeveloper** [comment]
![Снимок экрана от 2023-05-15 21-46-03](https://github.com/alexkdeveloper/bmi/assets/73014273/91b28175-7c8e-42c5-831b-8d57e5502948)

**Comment by alexkdeveloper** [comment]
Maybe it makes sense to replace it with something else?
What do you think?
