### ISSUE TITLE
Icon is not language universal

### ISSUE THREAD

**Issue by NathanBnm** [alexkdeveloper/bmi#6]
Using `BMI` as an icon is not a good practice because it is not language universal. The app icon should be understand by everyone independently of their language. For example French users won't understand what BMI means because it becomes IMC in French.

You should use a metaphor or something to represent your app like a weight scale for example.

You can refer to the [elementary Human Interface Guidelines](https://docs.elementary.io/hig/reference/iconography) for more info about iconography best practices.

**Comment by alexkdeveloper** [comment]
I found the image. It seems to me that it is perfect for this application.

https://cdn1.iconfinder.com/data/icons/ui-lines/24/Scale-256.png

**Comment by NathanBnm** [comment]
Good idea! I think you can create something like this. You can't just reuse the image you hav to create an original icon in SVG. You can also ask for help to the elementary community :smile:

**Comment by alexkdeveloper** [comment]
I changed the app icon. Now it looks like this:
https://github.com/alexkdeveloper/bmi/blob/main/data/icons/com.github.alexkdeveloper.bmi.svg

**Comment by NathanBnm** [comment]
Regarding the [elementary OS Human Interface Guidelines](https://docs.elementary.io/hig/reference/iconography) I assume you need to add some background and shadows.

**Comment by NathanBnm** [comment]
Maybe @Fatih20 could help
