### ISSUE TITLE
Question about methodology

### ISSUE THREAD

**Issue by edo0** [alexkdeveloper/bmi#7]
Having a background in health sciences, I was wondering why wrist circumference was chosen instead of waist circumference — the latter showing a superior correlation to visceral fat, and therefore being an arguably better predictor of complications such as metabolic syndrome, cardiovascular risk and diabetes.

**Comment by alexkdeveloper** [comment]
I did not create this method of calculating the body mass index. Such questions are best asked by its creators. I just wrote a program using this method. 
The circumference of the wrist is used to calculate the body type.

**Comment by edo0** [comment]
I understand.
Maybe it could be useful to add an extra, optional, field for waist circumference?
 This would vary based on racial group of origin. https://d3i71xaburhd42.cloudfront.net/bd1edbafe5885ca96db8635aab9549bcdb1ad6c3/2-Table1-1.png

https://www.health.gov.au/health-topics/overweight-and-obesity/bmi-and-waist#waist-measurement

**Comment by alexkdeveloper** [comment]
Thanks. I'll think about it.
